databases:
  - name: chatwoot
    region: frankfurt
    ipAllowList: []

services:
  - type: web
    name: chatwoot_web
    region: frankfurt
    runtime: ruby
    healthCheckPath: /up
    buildCommand: "bundle install"
    startCommand: "bin/rails server -p $PORT -e $RAILS_ENV"
    envVars:
      - key: WEB_CONCURRENCY
        value: 2
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase: 
          name: chatwoot
          property: connectionString
      - key: REDIS_URL
        value: redis://red-cqcibe08fa8c73cqt3i0:6379
  - type: worker
    name: chatwoot_sidekiq
    region: frankfurt
    runtime: ruby
    buildCommand: "bundle install"
    startCommand: "bundle exec sidekiq -C config/sidekiq.yml"
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase: 
          name: chatwoot
          property: connectionString
      - key: REDIS_URL
        value: redis://red-cqcibe08fa8c73cqt3i0:6379


  - type: redis
    name: chatwoot
    region: frankfurt
    ipAllowList: []